### ISSUE TITLE
月球尘埃的混凝土粉末dupe

### ISSUE THREAD

**Issue by Beafty** [SlimefunGuguProject/Galactifun#17]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Galactifun/issues)，且没有找到相同的问题

### 问题描述

月球尘埃在空中放下后会掉落一个淡灰色混凝土粉
火星尘埃同理

### 复现步骤

1、空中放一个月球尘埃(下面是空气方块)
火星尘埃同理
![XK{GV@ODY7ISJU0EK}SEB I](https://user-images.githubusercontent.com/40541355/182525200-8f55fbea-31f0-4303-a88b-77dd63d79bc8.png)
![(NZOWI O4W@QGZI 3YOD8Q5](https://user-images.githubusercontent.com/40541355/182525222-665122d6-7cec-4748-9968-be3d268ca3f8.png)
![TEUS CY3H}% BQ0RNR92A~1](https://user-images.githubusercontent.com/40541355/182525236-780f8d2c-3fa8-456e-88ea-209be460c854.png)
(月球尘埃还在）

### 预期行为

不掉落普通的粉

### 服务端软件

Paper

### Minecraft 版本

1.19

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

当时发给服主的是Slimefun-v2843a9c-canary 但是服务器重启过多次并且似乎没有关闭自动更新 估计是最新罢*

### 插件版本

8

**Comment by Beafty** [comment]
![image](https://user-images.githubusercontent.com/40541355/182526013-1322436d-8b6a-4b69-9a16-1d680fac6de9.png)

**Comment by ybw0014** [comment]
请分开汇报

**Comment by Violet-Nonbloosom** [comment]
Paper 1.19,2，build 18 仍然可以复现。

服务器环境如下图：

![图片](https://github.com/SlimefunGuguProject/Galactifun/assets/86547296/e4da3f26-f000-4f0a-982b-4f7c742ebf67)

**Comment by Violet-Nonbloosom** [comment]
该 dupe 生成掉落物的时机疑似为 `...slimefun4.implementation.BlockPhysicsListener.onBlockFall()` 。
这个函数是针对 `BlockStorage` 写的，和该附属自己用的 `blockMappings` 似乎有些不太融洽。
具体怎么解决我就不知道了，相信其他人的智慧。

**Comment by Violet-Nonbloosom** [comment]
上游也有汇报这个漏洞：Slimefun-Addon-Community#91
不过上游似乎不想修复它。

**Comment by ybw0014** [comment]
本体关于有物理效果方块的处理有问题，需要本体进行相关修复
