### ISSUE TITLE
火箭及其燃油dupe

### ISSUE THREAD

**Issue by Beafty** [SlimefunGuguProject/Galactifun#20]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Galactifun/issues)，且没有找到相同的问题

### 问题描述

弄个火箭 加点燃油 同时去地球的两个坐标 然后燃油就dupe了

### 复现步骤

整1个火箭
燃油加满 加的越多 dupe越多
然后两个人或者更多人一起选择不同的坐标发射
芜湖 多出来的燃油dupe了
gg

### 预期行为

多出来的燃油不应该复制
或者N个人不能同时使用一个火箭

### 服务端软件

Paper

### Minecraft 版本

1.19

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-v2843a9c-canary 以上版本

### 插件版本

8或者9

**Comment by ybw0014** [comment]
请使用新版本测试
