### ISSUE TITLE
宇航服无法抵抗 Slimefun 的辐射

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [SlimefunGuguProject/Galactifun#32]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Galactifun/issues)，且没有找到相同的问题

### 问题描述

根据 `SpaceSuit.java`，宇航服应当对蜜蜂伤害和核辐射具有抵抗力，与是否充入氧气、各项属性的强化等级**均无关**。
在穿戴潜水头盔（防化服套装的头盔）和**全套**宇航服（不包括头盔）的情况下，核辐射应当能被**完全避免**。
但事实并非如此，宇航服对于核辐射没有任何抵抗力。

个人预测是宇航服不兼容新版 Slimefun 的护甲系统所致。

### 复现步骤

1. 获取一个潜水头盔，以及一套宇航服。
2. 穿戴全套宇航服（除头盔），以及潜水头盔。
3. 获取一个起泡锭。
4. 观察到辐射值提升。

### 预期行为

宇航服应当对蜜蜂伤害和核辐射具有抵抗力。

一种可能的修复方案是，把宇航服的基类改为 `SlimefunArmorPiece`。

### 服务端软件

Paper

### Minecraft 版本

本插件不支持旧版本

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/Galactifun/assets/86547296/c1d6dd04-7108-49da-aeef-ed6cbebc1335)

### 插件版本

18

**Comment by ybw0014** [comment]
是因为潜水头盔。防化服需要套装才能生效，而你只装备了一件，那么就会触发辐射。
