### ISSUE TITLE
RADIATION_RESISTANCE_UPGRADE 翻译与同类物品格式不同

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [SlimefunGuguProject/Galactifun#33]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Galactifun/issues)，且没有找到相同的问题

### 问题描述

`RADIATION_RESISTANCE_UPGRADE` 在现行版本的翻译为“抗辐射升级机”。
这个翻译与同类物品（航天服的升级模块）格式不同，而且也是错误的，因为它不是完整的机器。

### 复现步骤

1. 打开指南，然后打开“星系”分类，最终打开“设备”分类。
2. 观察到 `RADIATION_RESISTANCE_UPGRADE` 被翻译为“抗辐射升级机”。

### 预期行为

`RADIATION_RESISTANCE_UPGRADE` 应翻译为“抗辐射升级模块”。

### 服务端软件

Paper

### Minecraft 版本

本插件不支持旧版本

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/Galactifun/assets/86547296/58f4aed2-7579-4b60-afd4-16d8096b68e2)

### 插件版本

18

**Comment by ybw0014** [comment]
提个PR？
