### ISSUE TITLE
`FIRESTORM` 翻译文本不一致

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [SlimefunGuguProject/Galactifun#35]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Galactifun/issues)，且没有找到相同的问题

### 问题描述

外星生物 `FIRESTORM` 的名称被翻译为“烈焰风暴”，但在死亡信息中却被翻译为“火爆者”。
两个翻译应该只有一个被保留。

### 复现步骤

1. 设法到达金星；
2. 观察到外星生物“烈焰风暴”
3. 被其击杀，消息显示为 “……因火爆者而触电身亡”。

### 预期行为

两个翻译中保留其中一个。

### 服务端软件

Paper

### Minecraft 版本

本插件不支持旧版本

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/Galactifun/assets/86547296/d8f11351-cdda-4d7e-ab24-b043fd41df16)

### 插件版本

18

**Comment by ybw0014** [comment]
你用的不是最新版
